### ISSUE TITLE
Dropdown Menu in mobile view

### ISSUE THREAD

**Issue by yash30201** [yash30201/aurora#3]
### Description
When the website is opened in smaller screen like that of smartphones, the navbar gets cluttered, so it's better to implement a dropdown menu in that case

**Comment by roshan0708** [comment]
Can you assign me this issue?

**Comment by yash30201** [comment]
> Can you assign me this issue?

Yeah sure @roshan0708 , I have assigned this to you.

**Comment by yash30201** [comment]
Closing as this is deprioritised now.
